### ISSUE TITLE
GCP todo list

### ISSUE THREAD

**Issue by maiquynhtruong** [maiquynhtruong/Senior-Design#2]
- [x] Go through [Getting Started](https://cloud.google.com/ml-engine/docs/tensorflow/getting-started-training-prediction) tutorial
- [x] Sign up for free credits
- [x] Create a project on GCP (?)
- [ ] Go through [low level intro to Tensorflow](https://www.tensorflow.org/guide/low_level_intro)
- [x] Change folder structure to [recommended project structure](https://cloud.google.com/ml-engine/docs/tensorflow/packaging-trainer#project-structure)
- [x] Upload stock data to Storage bucket
- [x] [Train](https://cloud.google.com/ml-engine/docs/tensorflow/training-overview) and run model locally with `python`
- [x] Run locally with `gcloud ml-engine local train`
- [x] Run and [deploy](https://cloud.google.com/ml-engine/docs/tensorflow/deploying-models) model online
- [ ] Write tests
- [ ] Set up TravisCI or something

**Comment by maiquynhtruong** [comment]
@changy66 let me know when you're done with the free credits. We will create a project tomorrow

**Comment by maiquynhtruong** [comment]
I've changed to [recommended project structure](https://cloud.google.com/ml-engine/docs/tensorflow/packaging-trainer#project-structure)  by gcp with commit 5f973713b98b5515d129732ed1eff539a12cdf54
